name: Deploy to AWS EC2

on:
  push:
    branches:
      - PROD
      - STAGING

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH fingerprint
        run: ssh-keyscan -H <EC2_PUBLIC_IP> >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./rest_service/ ubuntu@${{ secrets.PROD_IP }}:/home/ubuntu/rest_service/
        if: github.ref == 'refs/heads/PROD'

      - name: Deploy to EC2 Staging
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./rest_service/ ubuntu@${{ secrets.STAGING_IP }}:/home/ubuntu/rest_service/
        if: github.ref == 'refs/heads/STAGING'
