name: Deploy to AWS EC2

on:
  push:
    branches:
      - PROD
      - STAGING

env:
  PROD_IP: ${{ secrets.PROD_IP }}
  STAGING_IP: ${{ secrets.STAGING_IP }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - Print SSH key
        run: echo "${EC2_PRIVATE_KEY}"

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Configure SSH key
        run: |
          echo "${EC2_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH fingerprint for PROD
        run: ssh-keyscan -H ${{ env.PROD_IP }} >> ~/.ssh/known_hosts
        if: github.ref == 'refs/heads/PROD'

      - name: Add SSH fingerprint for STAGING
        run: ssh-keyscan -H ${{ env.STAGING_IP }} >> ~/.ssh/known_hosts
        if: github.ref == 'refs/heads/STAGING'

      - name: Install .NET SDK 7 on EC2 PROD
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} 'sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0'
        if: github.ref == 'refs/heads/PROD'

      - name: Install .NET SDK 7 on EC2 Staging
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ env.STAGING_IP }} 'sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0'
        if: github.ref == 'refs/heads/STAGING'

      - name: Deploy to EC2 PROD
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./rest_service/ ubuntu@${{ env.PROD_IP }}:/home/ubuntu/rest_service/
        if: github.ref == 'refs/heads/PROD'

      - name: Deploy to EC2 Staging
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./rest_service/ ubuntu@${{ env.STAGING_IP }}:/home/ubuntu/rest_service/
        if: github.ref == 'refs/heads/STAGING'

      - name: Create systemd service on EC2 PROD
        run: |
          echo "[Unit]
          Description=rest_service .NET Core Web API
          After=network.target
          
          [ Service ]
          WorkingDirectory=/home/ubuntu/rest_service
          ExecStart=/usr/bin/dotnet run
          Restart=always
          RestartSec=10
          SyslogIdentifier=rest_service
          User=ubuntu
          Environment=ASPNETCORE_ENVIRONMENT=Production
          
          [ Install ]
          WantedBy=multi-user.target" > rest_service.service
          scp -i ~/.ssh/id_rsa rest_service.service ubuntu@${{ env.PROD_IP }}:/home/ubuntu/rest_service.service
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.PROD_IP }} 'sudo mv /home/ubuntu/rest_service.service /etc/systemd/system/rest_service.service'
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.PROD_IP }} 'sudo systemctl enable rest_service.service'
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.PROD_IP }} 'sudo systemctl start rest_service.service'
        if: github.ref == 'refs/heads/PROD'

      - name: Create systemd service on EC2 Staging
        run: |
          echo "[Unit]
          Description=rest_service .NET Core Web API
          After=network.target
          
          [ Service ]
          WorkingDirectory=/home/ubuntu/rest_service
          ExecStart=/usr/bin/dotnet run
          Restart=always
          RestartSec=10
          SyslogIdentifier=rest_service
          User=ubuntu
          Environment=ASPNETCORE_ENVIRONMENT=Production
          
          [ Install ]
          WantedBy=multi-user.target" > rest_service.service
          scp -i ~/.ssh/id_rsa rest_service.service ubuntu@${{ env.STAGING_IP }}:/home/ubuntu/rest_service.service
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.STAGING_IP }} 'sudo mv /home/ubuntu/rest_service.service /etc/systemd/system/rest_service.service'
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.STAGING_IP }} 'sudo systemctl enable rest_service.service'
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.STAGING_IP }} 'sudo systemctl start rest_service.service'
        if: github.ref == 'refs/heads/STAGING'
