name: Manual Trigger Workflow
on:
  push:
    branches:
      - STAGING
  workflow_dispatch:
    inputs:
      just_some_random_number:
        description: 'Just choose a random number. Preferably 42.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          echo foo
