name: Manual Trigger Workflow
on:
  push:
    branches:
      - STAGING
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          echo foo

      # Add your build and deployment steps here
      # For example:
      # - name: Build project
      #   run: |
      #     # Build commands go here

      # - name: Deploy to production
      #   if: github.event_name == 'workflow_dispatch' # Optional, you can conditionally run deployment based on the event name
      #   run: |
      #     # Deployment commands go here
