name: Manual Trigger Workflow
on:
  push:
    branches:
      - STAGING
  workflow_dispatch:
    # To allow manual triggering, we need to specify an input
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        # Set the input as not required, so it's optional during manual triggering
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          echo foo
